<?php
/**
* @file
* Implements various blocks to improve pending content workflow.
*/

/**
* Implements as_approval_block_info().
*/

function as_approval_block_info() {

	$blocks['last_offers'] = array(
		'info' => t('Last offers'),
		'status' => TRUE,
		'region' => 'sidebar_second',
		'weight' => 0,
		'visibility' => 1,);

	$blocks['top_offers'] = array(
		'info'	=> t('Top offers'),
			'status'	=> TRUE,
			'region'	=> 'sidebar_second',
			'weight'	=> 0,
			'visibility' => 1,
		);

	return $blocks;
}

/**
* Implements hook_block_configure().
*/
function as_approval_block_configure($delta) {
	$form = array();
	switch($delta) {
	case 'last_offers':
		$form['last_offers_count'] = array(
			'#type' => 'textfield',
			'#title' => t('Configure Number of Offers to Display'),
			'#size' => 6,
			'#description' => t('Enter the number of last offers that will appear in the
			block.'),
			'#default_value' => variable_get('last_offers_count', 5),
		);
		break;

	case 'top_offers':
		$form['top_offers_count'] = array(
			'#type' => 'textfield',
			'#title' => t('Configure Number of top offfers to Display'),
			'#size' => 6,
			'#description' => t('Enter the number of top offers that will appear in the
			block.'),
			'#default_value' => variable_get('top_offers_count', 5),
		);
		break;

	}
	return $form;
}


/**
 * Implements hook_block_save().
 */
function as_approval_block_save($delta = '', $edit = array()) {
	switch($delta) {
	case 'last_offers':
		variable_set('last_offers_count', (int)$edit['last_offers_count']);
		break;
	case 'top_offers':
		variable_set('top_offers_count', (int)$edit['top_offers_count']);
		break;
	}
	return;
}

function as_approval_block_view($delta = '') {
	
	switch ($delta) {
	case 'last_offers':
		$block['subject'] = t('Last offers');
		$block['content'] = as_approval_block_contents($delta);
		return $block;
		break;
	case 'top_offers':
		$block['subject'] = t('Top offers');
		$block['content'] = as_approval_block_contents($delta);
		return $block;
		break;
	}
}


/**
 * A module-defined block content function.
 */
function as_approval_block_contents($delta) {

	switch ($delta) {
	
	case 'last_offers':
			$nbr_nodes = variable_get('top_offers_count', 5);
			$result = db_query_range('SELECT nid, title FROM {node} WHERE
				status = 1', 0, $nbr_nodes);
			$items = array();
			foreach ($result as $row) {
				$items[] = l($row->title, 'node/'.$row->nid);
			return array('#markup' => theme('item_list', array('items' => $items)));
			}
				break;

	case 'top_offers':
			$nbr_nodes = variable_get('top_offers_count', 5);
			$result = db_query_range('SELECT nid, title FROM {node} WHERE
				status = 1', 0, $nbr_nodes);
			$items = array();
			foreach ($result as $row) {
				$items[] = l($row->title, 'node/'.$row->nid);
			return array('#markup' => theme('item_list', array('items' => $items)));
			}
			break;
	}
}

